@MusicAPI_HostAddress = http://localhost:5173

GET {{MusicAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET  http://localhost:5173/api/music

###
POST http://localhost:5173/api/music
Content-Type: application/json

{
  "Title": "Todo6",
  "Description": "Todo 6",
  "IsDone": true,
  "CreatedAt": "2020-01-01"

}
